export const longestRepeatingCharReplacementCode = [
  { line: 1, text: "function characterReplacement(s: string, k: number): number {" },
  { line: 2, text: "  const freq = new Map<string, number>();" },
  { line: 3, text: "  let maxFreq = 0;" },
  { line: 4, text: "  let longestSub = 0;" },
  { line: 5, text: "  let left = 0;" },
  { line: 6, text: "  let right = 0;" },
  { line: 7, text: "  while (right < s.length) {" },
  { line: 8, text: "    const ch = s[right];" },
  { line: 9, text: "    freq.set(ch, (freq.get(ch) || 0) + 1);" },
  { line: 10, text: "    maxFreq = Math.max(maxFreq, freq.get(ch)!);" },
  { line: 11, text: "    while (right - left + 1 - maxFreq > k) {" },
  { line: 12, text: "      const leftCh = s[left];" },
  { line: 13, text: "      freq.set(leftCh, freq.get(leftCh)! - 1);" },
  { line: 14, text: "      left++;" },
  { line: 15, text: "    }" },
  { line: 16, text: "    longestSub = Math.max(longestSub, right - left + 1);" },
  { line: 17, text: "    right++;" },
  { line: 18, text: "  }" },
  { line: 19, text: "  return longestSub;" },
  { line: 20, text: "}" },
];
