export const balancedTreeCode = [
  { line: 1, text: "function isBalanced(root) {" },
  { line: 2, text: "  if (!root) return true;" },
  { line: 3, text: "  let result = true;" },
  { line: 4, text: "" },
  { line: 5, text: "  function dfs(node) {" },
  { line: 6, text: "    if (!node) return 0;" },
  { line: 7, text: "    const left = dfs(node.left);" },
  { line: 8, text: "    const right = dfs(node.right);" },
  { line: 9, text: "    if (Math.abs(left - right) > 1) result = false;" },
  { line: 10, text: "    return 1 + Math.max(left, right);" },
  { line: 11, text: "  }" },
  { line: 12, text: "" },
  { line: 13, text: "  dfs(root);" },
  { line: 14, text: "  return result;" },
  { line: 15, text: "}" },
];
