export const kthSmallestCode = [
  { line: 1, text: "function kthSmallest(root: TreeNode | null, k: number): number {" },
  { line: 2, text: "  let count = 0, result = 0;" },
  { line: 3, text: "" },
  { line: 4, text: "  function dfs(node: TreeNode | null) {" },
  { line: 5, text: "    if (!node) return;" },
  { line: 6, text: "    dfs(node.left);" },
  { line: 7, text: "    count++;" },
  { line: 8, text: "    if (count === k) {" },
  { line: 9, text: "      result = node.val;" },
  { line: 10, text: "      return;" },
  { line: 11, text: "    }" },
  { line: 12, text: "    dfs(node.right);" },
  { line: 13, text: "  }" },
  { line: 14, text: "" },
  { line: 15, text: "  dfs(root);" },
  { line: 16, text: "  return result;" },
  { line: 17, text: "}" },
];
