export const pathSumIICode = [
  { line: 1, text: "function pathSumII(root: TreeNode | null, targetSum: number): number[][] {" },
  { line: 2, text: "  if (!root) return [];" },
  { line: 3, text: "  const result: number[][] = [];" },
  { line: 4, text: "  function dfs(node: TreeNode | null, traversed: number[], sum: number) {" },
  { line: 5, text: "    if (!node) return;" },
  { line: 6, text: "    sum += node.val;" },
  { line: 7, text: "    traversed.push(node.val);" },
  { line: 8, text: "    if (!node.left && !node.right && sum === targetSum)" },
  { line: 9, text: "      result.push([...traversed]);" },
  { line: 10, text: "    dfs(node.left, traversed, sum);" },
  { line: 11, text: "    dfs(node.right, traversed, sum);" },
  { line: 12, text: "    traversed.pop();" },
  { line: 13, text: "    sum -= node.val;" },
  { line: 14, text: "  }" },
  { line: 15, text: "  dfs(root, [], 0);" },
  { line: 16, text: "  return result;" },
  { line: 17, text: "}" },
];
