export const treeBuilderCode = [
  { line: 1, text: "function buildTree(arr: (number | null)[]): TreeNode | null {" },
  { line: 2, text: "  if (!arr.length || arr[0] === null) return null;" },
  { line: 3, text: "  const root = new TreeNode(arr[0]);" },
  { line: 4, text: "  const queue: TreeNode[] = [root];" },
  { line: 5, text: "  let i = 1;" },
  { line: 6, text: "  while (i < arr.length && queue.length > 0) {" },
  { line: 7, text: "    const parent = queue.shift()!;" },
  { line: 8, text: "    if (i < arr.length && arr[i] !== null) {" },
  { line: 9, text: "      parent.left = new TreeNode(arr[i]);" },
  { line: 10, text: "      queue.push(parent.left);" },
  { line: 11, text: "    }" },
  { line: 12, text: "    i++;" },
  { line: 13, text: "    if (i < arr.length && arr[i] !== null) {" },
  { line: 14, text: "      parent.right = new TreeNode(arr[i]);" },
  { line: 15, text: "      queue.push(parent.right);" },
  { line: 16, text: "    }" },
  { line: 17, text: "    i++;" },
  { line: 18, text: "  }" },
  { line: 19, text: "  return root;" },
  { line: 20, text: "}" },
];
