export const widthOfBinaryTreeCode = [
  { line: 1, text: "function widthOfBinaryTree(root: TreeNode | null): number {" },
  { line: 2, text: "  if (!root) return 0;" },
  { line: 3, text: "  let queue: [TreeNode, number][] = [[root, 0]];" },
  { line: 4, text: "  let maxWidth = 0;" },
  { line: 5, text: "  while (queue.length) {" },
  { line: 6, text: "    let levelSize = queue.length;" },
  { line: 7, text: "    const startIndex = queue[0][1];" },
  { line: 8, text: "    let first = 0, last = 0;" },
  { line: 9, text: "    for (let i = 0; i < levelSize; i++) {" },
  { line: 10, text: "      const [node, index] = queue.shift()!;" },
  { line: 11, text: "      const normalizedIndex = index - startIndex;" },
  { line: 12, text: "      if (i === 0) first = normalizedIndex;" },
  { line: 13, text: "      if (i === levelSize - 1) last = normalizedIndex;" },
  { line: 14, text: "      if (node.left) queue.push([node.left, 2 * normalizedIndex + 1]);" },
  { line: 15, text: "      if (node.right) queue.push([node.right, 2 * normalizedIndex + 2]);" },
  { line: 16, text: "    }" },
  { line: 17, text: "    maxWidth = Math.max(maxWidth, last - first + 1);" },
  { line: 18, text: "  }" },
  { line: 19, text: "  return maxWidth;" },
  { line: 20, text: "}" },
];
