export const zigzagLevelOrderCode = [
  { line: 1, text: "function zigzagLevelOrder(root: TreeNode | null): number[][] {" },
  { line: 2, text: "  if (!root) return [];" },
  { line: 3, text: "  const result: number[][] = [];" },
  { line: 4, text: "  const queue: TreeNode[] = [root];" },
  { line: 5, text: "  let inverted = true;" },
  { line: 6, text: "  while (queue.length) {" },
  { line: 7, text: "    const levels = queue.length;" },
  { line: 8, text: "    const level: number[] = [];" },
  { line: 9, text: "    inverted = !inverted;" },
  { line: 10, text: "    for (let i = 0; i < levels; i++) {" },
  { line: 11, text: "      const node = queue.shift()!;" },
  { line: 12, text: "      level.push(node.val);" },
  { line: 13, text: "      if (node.left) queue.push(node.left);" },
  { line: 14, text: "      if (node.right) queue.push(node.right);" },
  { line: 15, text: "    }" },
  { line: 16, text: "    result.push(inverted ? level.reverse() : level);" },
  { line: 17, text: "  }" },
  { line: 18, text: "  return result;" },
  { line: 19, text: "}" },
];
