export const asteroidCollisionCode = [
  { line: 1, text: "function asteroidCollision(asteroids: number[]): number[] {" },
  { line: 2, text: "  const stack: number[] = [];" },
  { line: 3, text: "  for (let asteroid of asteroids) {" },
  { line: 4, text: "    let destroyed: boolean = false;" },
  { line: 5, text: "    while (stack.length && asteroid < 0 && stack[stack.length - 1] > 0) {" },
  { line: 6, text: "      let top = stack[stack.length - 1];" },
  { line: 7, text: "      let abs = Math.abs(asteroid);" },
  { line: 8, text: "      if (top > abs) {" },
  { line: 9, text: "        destroyed = true;" },
  { line: 10, text: "        break;" },
  { line: 11, text: "      } else if (top === abs) {" },
  { line: 12, text: "        destroyed = true;" },
  { line: 13, text: "        stack.pop();" },
  { line: 14, text: "        break;" },
  { line: 15, text: "      } else stack.pop();" },
  { line: 16, text: "    }" },
  { line: 17, text: "    if (!destroyed) stack.push(asteroid);" },
  { line: 18, text: "  }" },
  { line: 19, text: "  return stack;" },
  { line: 20, text: "}" },
];
