export const kokoEatingBananasCode = [
  { line: 1, text: "function minEatingSpeed(piles: number[], h: number): number {" },
  { line: 2, text: "  let left = 1;" },
  { line: 3, text: "  let right = Math.max(...piles);" },
  { line: 4, text: "  function getHours(piles: number[], mid: number): number {" },
  { line: 5, text: "    let th = 0;" },
  { line: 6, text: "    for (let pile of piles) th += Math.ceil(pile / mid);" },
  { line: 7, text: "    return th;" },
  { line: 8, text: "  }" },
  { line: 9, text: "  while (left <= right) {" },
  { line: 10, text: "    let mid = Math.floor((left + right) / 2);" },
  { line: 11, text: "    let totalHours = getHours(piles, mid);" },
  { line: 12, text: "    if (totalHours > h) {" },
  { line: 13, text: "      left = mid + 1;" },
  { line: 14, text: "    } else {" },
  { line: 15, text: "      right = mid - 1;" },
  { line: 16, text: "    }" },
  { line: 17, text: "  }" },
  { line: 18, text: "  return left;" },
  { line: 19, text: "}" },
];
