export const searchMatrixCode = [
  { line: 1, text: "function searchMatrix(matrix: number[][], target: number): boolean {" },
  { line: 2, text: "  let m = matrix.length;" },
  { line: 3, text: "  let n = matrix[0].length;" },
  { line: 4, text: "  let left = 0;" },
  { line: 5, text: "  let right = m * n - 1;" },
  { line: 6, text: "  while (left <= right) {" },
  { line: 7, text: "    let mid = Math.floor((left + right) / 2);" },
  { line: 8, text: "    let row = Math.floor(mid / n);" },
  { line: 9, text: "    let column = mid % n;" },
  { line: 10, text: "    if (matrix[row][column] < target) {" },
  { line: 11, text: "      left = mid + 1;" },
  { line: 12, text: "    } else if (matrix[row][column] > target) {" },
  { line: 13, text: "      right = mid - 1;" },
  { line: 14, text: "    } else {" },
  { line: 15, text: "      return true;" },
  { line: 16, text: "    }" },
  { line: 17, text: "  }" },
  { line: 18, text: "  return false;" },
  { line: 19, text: "}" },
];
