export const searchRotatedCode = [
  { line: 1, text: "function searchRotated(nums: number[], target: number): number {" },
  { line: 2, text: "  let left = 0;" },
  { line: 3, text: "  let right = nums.length - 1;" },
  { line: 4, text: "  while (left < right) {" },
  { line: 5, text: "    let mid = Math.floor((left + right) / 2);" },
  { line: 6, text: "    if (nums[mid] < nums[right]) right = mid;" },
  { line: 7, text: "    else left = mid + 1;" },
  { line: 8, text: "  }" },
  { line: 9, text: "  let minIndex = left;" },
  { line: 10, text: "  if (target >= nums[left] && target <= nums[nums.length - 1]) {" },
  { line: 11, text: "    right = nums.length - 1;" },
  { line: 12, text: "  } else {" },
  { line: 13, text: "    left = 0;" },
  { line: 14, text: "    right = minIndex - 1;" },
  { line: 15, text: "  }" },
  { line: 16, text: "" },
  { line: 17, text: "  while (left <= right) {" },
  { line: 18, text: "    let mid = Math.floor((left + right) / 2);" },
  { line: 19, text: "    if (nums[mid] < target) left = mid + 1;" },
  { line: 20, text: "    else if (nums[mid] > target) right = mid - 1;" },
  { line: 21, text: "    else return mid;" },
  { line: 22, text: "  }" },
  { line: 23, text: "  return -1;" },
  { line: 24, text: "}" },
];
