export const shipWithinDaysCode = [
  { line: 1, text: "function shipWithinDays(weights: number[], days: number): number {" },
  { line: 2, text: "  let left = Math.max(...weights);" },
  { line: 3, text: "  let right = weights.reduce((a, b) => a + b, 0);" },
  { line: 4, text: "  while (left < right) {" },
  { line: 5, text: "    let mid = Math.floor((left + right) / 2);" },
  { line: 6, text: "    let reqDays = getTotalDays(weights, mid);" },
  { line: 7, text: "    if (reqDays > days) left = mid + 1;" },
  { line: 8, text: "    else right = mid;" },
  { line: 9, text: "  }" },
  { line: 10, text: "  return left;" },
  { line: 11, text: "}" },
  { line: 12, text: "function getTotalDays(weights: number[], capacity: number): number {" },
  { line: 13, text: "  let totalDays = 1, currentWeight = 0;" },
  { line: 14, text: "  for (let weight of weights) {" },
  { line: 15, text: "    if (currentWeight + weight > capacity) {" },
  { line: 16, text: "      totalDays++; currentWeight = 0;" },
  { line: 17, text: "    }" },
  { line: 18, text: "    currentWeight += weight;" },
  { line: 19, text: "  }" },
  { line: 20, text: "  return totalDays;" },
  { line: 21, text: "}" },
];
