export const isValidSudokuCode = [
  { line: 1, text: "function isValidSudoku(board: string[][]): boolean {" },
  { line: 2, text: "  const rows = Array.from({ length: 9 }, () => new Set<string>());" },
  { line: 3, text: "  const cols = Array.from({ length: 9 }, () => new Set<string>());" },
  { line: 4, text: "  const boxes = Array.from({ length: 9 }, () => new Set<string>());" },
  { line: 5, text: "  for (let r = 0; r < rows.length; r++) {" },
  { line: 6, text: "    for (let c = 0; c < cols.length; c++) {" },
  { line: 7, text: "      const value = board[r][c];" },
  { line: 8, text: "      if (value === \".\") continue;" },
  { line: 9, text: "      const box = Math.floor(r / 3) * 3 + Math.floor(c / 3);" },
  { line: 10, text: "" },
  { line: 11, text: "      if (rows[r].has(value) || cols[c].has(value) || boxes[box].has(value)) {" },
  { line: 12, text: "        return false;" },
  { line: 13, text: "      }" },
  { line: 14, text: "      rows[r].add(value);" },
  { line: 15, text: "      cols[c].add(value);" },
  { line: 16, text: "      boxes[box].add(value);" },
  { line: 17, text: "    }" },
  { line: 18, text: "  }" },
  { line: 19, text: "  return true;" },
  { line: 20, text: "}" },
];
