export const sortedSquaresCode = [
  { line: 1, text: "function sortedSquares(nums: number[]): number[] {" },
  { line: 2, text: "  const result = new Array(nums.length);" },
  { line: 3, text: "  let left = 0;" },
  { line: 4, text: "  let right = nums.length - 1;" },
  { line: 5, text: "  let pos = nums.length - 1;" },
  { line: 6, text: "  while (left <= right) {" },
  { line: 7, text: "    const leftSq = nums[left] ** 2;" },
  { line: 8, text: "    const rightSq = nums[right] ** 2;" },
  { line: 9, text: "    if (leftSq > rightSq) {" },
  { line: 10, text: "      result[pos] = leftSq;" },
  { line: 11, text: "      left++;" },
  { line: 12, text: "    } else {" },
  { line: 13, text: "      result[pos] = rightSq;" },
  { line: 14, text: "      right--;" },
  { line: 15, text: "    }" },
  { line: 16, text: "    pos--;" },
  { line: 17, text: "  }" },
  { line: 18, text: "  return result;" },
  { line: 19, text: "}" },
];
