export const threeSumCode = [
  { line: 1, text: "function threeSum(nums: number[]): number[][] {" },
  { line: 2, text: "  if (!nums.length) return [];" },
  { line: 3, text: "  nums.sort((a, b) => a - b);" },
  { line: 4, text: "  const result: number[][] = [];" },
  { line: 5, text: "  const n = nums.length;" },
  { line: 6, text: "  for (let i = 0; i < n - 2; i++) {" },
  { line: 7, text: "    if (i > 0 && nums[i] === nums[i - 1]) continue;" },
  { line: 8, text: "    let j = i + 1;" },
  { line: 9, text: "    let k = n - 1;" },
  { line: 10, text: "    while (j < k) {" },
  { line: 11, text: "      const sum = nums[i] + nums[j] + nums[k];" },
  { line: 12, text: "      if (sum === 0) {" },
  { line: 13, text: "        result.push([nums[i], nums[j], nums[k]]);" },
  { line: 14, text: "        j++;" },
  { line: 15, text: "        k--;" },
  { line: 16, text: "        while (j < k && nums[j] === nums[j - 1]) j++;" },
  { line: 17, text: "        while (j < k && nums[k] === nums[k + 1]) k--;" },
  { line: 18, text: "      } else if (sum < 0) {" },
  { line: 19, text: "        j++;" },
  { line: 20, text: "      } else {" },
  { line: 21, text: "        k--;" },
  { line: 22, text: "      }" },
  { line: 23, text: "    }" },
  { line: 24, text: "  }" },
  { line: 25, text: "  return result;" },
  { line: 26, text: "}" },
];
