export const partitionListCode = [
  { line: 1, text: "function partition(head: ListNode | null, x: number): ListNode | null {" },
  { line: 2, text: "  if (!head || !head.next) return head;" },
  { line: 3, text: "  const dummyLess = new ListNode(-1);" },
  { line: 4, text: "  const dummyMore = new ListNode(-1);" },
  { line: 5, text: "  let t1 = dummyLess;" },
  { line: 6, text: "  let t2 = dummyMore;" },
  { line: 7, text: "  let curr = head;" },
  { line: 8, text: "  while (curr) {" },
  { line: 9, text: "    if (curr.val < x) {" },
  { line: 10, text: "      t1.next = curr;" },
  { line: 11, text: "      t1 = curr;" },
  { line: 12, text: "    } else {" },
  { line: 13, text: "      t2.next = curr;" },
  { line: 14, text: "      t2 = curr;" },
  { line: 15, text: "    }" },
  { line: 16, text: "    curr = curr.next!;" },
  { line: 17, text: "  }" },
  { line: 18, text: "  t2.next = null;" },
  { line: 19, text: "  t1.next = dummyMore.next;" },
  { line: 20, text: "  return dummyLess.next;" },
  { line: 21, text: "}" },
];
