export const removeNthFromEndCode = [
  { line: 1, text: "function removeNthFromEndOptimal(head: ListNode | null, n: number): ListNode | null {" },
  { line: 2, text: "  const dummy = new ListNode(0, head);" },
  { line: 3, text: "  let slow = dummy;" },
  { line: 4, text: "  let fast = dummy;" },
  { line: 5, text: "" },
  { line: 6, text: "  for (let i = 0; i <= n; i++) {" },
  { line: 7, text: "    fast = fast.next!;" },
  { line: 8, text: "  }" },
  { line: 9, text: "" },
  { line: 10, text: "  while (fast) {" },
  { line: 11, text: "    slow = slow.next!;" },
  { line: 12, text: "    fast = fast.next!;" },
  { line: 13, text: "  }" },
  { line: 14, text: "" },
  { line: 15, text: "  slow.next = slow.next!.next;" },
  { line: 16, text: "" },
  { line: 17, text: "  return dummy.next;" },
  { line: 18, text: "}" },
];
