export const reorderListCode = [
  { line: 1, text: "function reorderList(head: ListNode | null): void {" },
  { line: 2, text: "  if (!head || !head.next) return;" },
  { line: 3, text: "" },
  { line: 4, text: "  let slow: ListNode = head;" },
  { line: 5, text: "  let fast: ListNode = head;" },
  { line: 6, text: "  while (fast.next !== null && fast.next.next !== null) {" },
  { line: 7, text: "    slow = slow.next!;" },
  { line: 8, text: "    fast = fast.next.next;" },
  { line: 9, text: "  }" },
  { line: 10, text: "  " },
  { line: 11, text: "  let second: ListNode | null = slow.next;" },
  { line: 12, text: "  slow.next = null;" },
  { line: 13, text: "  let prev: ListNode | null = null;" },
  { line: 14, text: "  while (second !== null) {" },
  { line: 15, text: "    const next: ListNode | null = second.next;" },
  { line: 16, text: "    second.next = prev;" },
  { line: 17, text: "    prev = second;" },
  { line: 18, text: "    second = next;" },
  { line: 19, text: "  }" },
  { line: 20, text: "  second = prev;" },
  { line: 21, text: "  let first: ListNode | null = head;" },
  { line: 22, text: "  while (second !== null) {" },
  { line: 23, text: "    let firstNext: ListNode | null = first.next!;" },
  { line: 24, text: "    let secondNext: ListNode | null = second.next;" },
  { line: 25, text: "    first.next = second;" },
  { line: 26, text: "    second.next = firstNext;" },
  { line: 27, text: "    first = firstNext;" },
  { line: 28, text: "    second = secondNext;" },
  { line: 29, text: "  }" },
  { line: 30, text: "}" },
];
