export const sortListCode = [
  { line: 1, text: "function sortList(head: ListNode | null): ListNode | null {" },
  { line: 2, text: "  if (!head || !head.next) return head;" },
  { line: 3, text: "  let slow = head;" },
  { line: 4, text: "  let fast = head;" },
  { line: 5, text: "  while (fast.next && fast.next.next) {" },
  { line: 6, text: "    slow = slow.next!;" },
  { line: 7, text: "    fast = fast.next.next;" },
  { line: 8, text: "  }" },
  { line: 9, text: "  const mid = slow.next;" },
  { line: 10, text: "  slow.next = null;" },
  { line: 11, text: "  const left = sortList(head);" },
  { line: 12, text: "  const right = sortList(mid);" },
  { line: 13, text: "  return merge(left, right);" },
  { line: 14, text: "}" },
  { line: 15, text: "" },
  { line: 16, text: "function merge(l1: ListNode | null, l2: ListNode | null): ListNode | null {" },
  { line: 17, text: "  const dummy = new ListNode(-1);" },
  { line: 18, text: "  let curr = dummy;" },
  { line: 19, text: "  while (l1 && l2) {" },
  { line: 20, text: "    if (l1.val > l2.val) {" },
  { line: 21, text: "      curr.next = l2;" },
  { line: 22, text: "      l2 = l2.next;" },
  { line: 23, text: "    } else {" },
  { line: 24, text: "      curr.next = l1;" },
  { line: 25, text: "      l1 = l1.next;" },
  { line: 26, text: "    }" },
  { line: 27, text: "    curr = curr.next;" },
  { line: 28, text: "  }" },
  { line: 29, text: "  curr.next = l1 ?? l2;" },
  { line: 30, text: "  return dummy.next;" },
  { line: 31, text: "}" },
];
