import type { SourceCodeLine } from "../../shared/types";

export const source: SourceCodeLine[] = [
  { line: 1, text: "class MinHeap {" },
  { line: 2, text: "  private heap: number[] = [];" },
  { line: 3, text: "" },
  { line: 4, text: "  public add(value: number): void {" },
  { line: 5, text: "    this.heap.push(value);" },
  { line: 6, text: "    this._heapifyUp();" },
  { line: 7, text: "  }" },
  { line: 8, text: "" },
  { line: 9, text: "  public poll(): number | null {" },
  { line: 10, text: "    if (this.heap.length === 0) return null;" },
  { line: 11, text: "    if (this.heap.length === 1) return this.heap.pop()!;" },
  { line: 12, text: "    const root = this.heap[0];" },
  { line: 13, text: "    this.heap[0] = this.heap.pop()!;" },
  { line: 14, text: "    this._heapifyDown();" },
  { line: 15, text: "    return root;" },
  { line: 16, text: "  }" },
  { line: 17, text: "" },
  { line: 18, text: "  private _heapifyUp(): void {" },
  { line: 19, text: "    let index = this.heap.length - 1;" },
  { line: 20, text: "    while (index > 0) {" },
  { line: 21, text: "      const parentIndex = Math.floor((index - 1) / 2);" },
  { line: 22, text: "      if (this.heap[parentIndex] <= this.heap[index]) break;" },
  { line: 23, text: "      [this.heap[parentIndex], this.heap[index]] = [this.heap[index], this.heap[parentIndex]];" },
  { line: 24, text: "      index = parentIndex;" },
  { line: 25, text: "    }" },
  { line: 26, text: "  }" },
  { line: 27, text: "" },
  { line: 28, text: "  private _heapifyDown(): void {" },
  { line: 29, text: "    let index = 0;" },
  { line: 30, text: "    const length = this.heap.length;" },
  { line: 31, text: "    while (true) {" },
  { line: 32, text: "      const leftChildIndex = 2 * index + 1;" },
  { line: 33, text: "      const rightChildIndex = 2 * index + 2;" },
  { line: 34, text: "      let smallestIndex = index;" },
  { line: 35, text: "      if (leftChildIndex < length && this.heap[leftChildIndex] < this.heap[smallestIndex]) {" },
  { line: 36, text: "        smallestIndex = leftChildIndex;" },
  { line: 37, text: "      }" },
  { line: 38, text: "      if (rightChildIndex < length && this.heap[rightChildIndex] < this.heap[smallestIndex]) {" },
  { line: 39, text: "        smallestIndex = rightChildIndex;" },
  { line: 40, text: "      }" },
  { line: 41, text: "      if (smallestIndex === index) break;" },
  { line: 42, text: "      [this.heap[index], this.heap[smallestIndex]] = [this.heap[smallestIndex], this.heap[index]];" },
  { line: 43, text: "      index = smallestIndex;" },
  { line: 44, text: "    }" },
  { line: 45, text: "  }" },
  { line: 46, text: "}" },
];

export default source;
